version: '3'
services:
  service:
    build: '.'
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_URL=jdbc:postgresql://database:5432/db
      - DB_PASSWORD=postgres123
  database:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432