version: '3'
services:
  app:
    build: .
    image: message-scheduler
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_URL=jdbc:postgresql://db:5432/db
      - DB_PASSWORD=postgres123
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - TZ=GMT
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus:v2.25.0
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:7.4.2
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/