apiVersion: v1
kind: Service
metadata:
  labels:
    app: scheduler
  name: scheduler-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: scheduler
  type: NodePort
status:
  loadBalancer: { }
