apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  labels:
    app: scheduler
data:
  DB_USER: postgres
  DB_URL: jdbc:postgresql://10.74.0.3:5432/postgresdb
  DB_PASSWORD: postgres123
