apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: message-scheduler:latest
        name: message-scheduler
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_USER
            value: postgres
          - name: DB_URL
            value: jdbc:postgresql://db:5432/db
          - name: DB_PASSWORD
            value: postgres123
        ports:
          - containerPort: 8080
