apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  strategy: { }
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - image: erickopelt/message-scheduler:latest
          name: message-scheduler
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: scheduler-config
          ports:
            - containerPort: 8080